#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
PUB-003 manuscript patcher

Patches the PUB-002 manuscript using publication assets generated by
pub003_build_publication_assets.py.

It updates:
- data-derived result tables;
- machine-derived Figures 1, 3, and 4;
- inserts a direct full-vs-pair offset comparison figure;
- replaces the code/data availability placeholder;
- advances the manuscript label to v0.5 / PUB-003.

Figure 2 (conceptual matched-successor schematic) is intentionally retained as a
schematic and is not claimed to be machine-derived data.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import shutil

import pandas as pd
from docx import Document
from docx.shared import Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn


def replace_text(p, text: str) -> None:
    for r in p.runs:
        r.text = ""
    p.add_run(text)


def move_paragraph_before(paragraph, target):
    target._p.addprevious(paragraph._p)


def paragraph_has_picture(p) -> bool:
    return bool(p._p.xpath(".//w:drawing") or p._p.xpath(".//w:pict"))


def remove_preceding_picture(caption):
    node = caption._p.getprevious()
    while node is not None:
        # Stop if prior non-empty text paragraph is reached.
        texts = node.xpath(".//w:t/text()")
        has_draw = bool(node.xpath(".//w:drawing") or node.xpath(".//w:pict"))
        if has_draw:
            node.getparent().remove(node)
            return True
        if any(str(x).strip() for x in texts):
            return False
        prev = node.getprevious()
        node = prev
    return False


def insert_picture_before(doc, caption, image_path: Path, width_inches: float = 6.2):
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.add_run().add_picture(str(image_path), width=Inches(width_inches))
    move_paragraph_before(p, caption)


def replace_figure(doc, caption_prefix: str, image_path: Path, new_caption: str):
    caption = next(p for p in doc.paragraphs if p.text.startswith(caption_prefix))
    remove_preceding_picture(caption)
    insert_picture_before(doc, caption, image_path)
    replace_text(caption, new_caption)
    caption.alignment = WD_ALIGN_PARAGRAPH.CENTER


def insert_figure_before_heading(doc, heading_text: str, image_path: Path, caption_text: str):
    heading = next(p for p in doc.paragraphs if p.text.strip() == heading_text)
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.add_run().add_picture(str(image_path), width=Inches(6.2))
    move_paragraph_before(p, heading)

    cap = doc.add_paragraph(caption_text)
    cap.alignment = WD_ALIGN_PARAGRAPH.CENTER
    move_paragraph_before(cap, heading)


def table_by_headers(doc, headers):
    want = [x.lower() for x in headers]
    for t in doc.tables:
        got = [c.text.strip().lower() for c in t.rows[0].cells]
        if got == want:
            return t
    raise KeyError(f"table not found: {headers}")


def rewrite_rows(table, rows):
    # Keep header, delete data rows.
    while len(table.rows) > 1:
        tr = table.rows[-1]._tr
        tr.getparent().remove(tr)
    for vals in rows:
        cells = table.add_row().cells
        for i, v in enumerate(vals):
            cells[i].text = str(v)


def fmt(x, digits=5):
    try:
        return f"{float(x):.{digits}f}"
    except Exception:
        return str(x)


def main():
    ap = argparse.ArgumentParser(description="Patch PUB-002 manuscript with PUB-003 assets")
    ap.add_argument("--manuscript-in", required=True, type=Path)
    ap.add_argument("--assets-dir", required=True, type=Path)
    ap.add_argument("--manuscript-out", required=True, type=Path)
    args = ap.parse_args()

    doc = Document(args.manuscript_in)
    pub = args.assets_dir / "publication"
    figs = pub / "figures"
    tabs = pub / "tables"

    # Version.
    for p in doc.paragraphs:
        if p.text.startswith("Submission draft v0.4"):
            replace_text(p, "Submission draft v0.5 / PUB-003 — machine-derived figures, tables, and release pass")
            break

    # Figures: replace data/research-summary figures.
    replace_figure(
        doc,
        "Figure 1.",
        figs / "figure_1_falsification_path.png",
        "Figure 1. Machine-generated falsification and narrowing path reconstructed from the frozen B50 publication lineage."
    )
    replace_figure(
        doc,
        "Figure 3.",
        figs / "figure_4_shapley_contributions.png",
        "Figure 3. Exact Shapley decomposition generated directly from the frozen B50.11 output table."
    )
    replace_figure(
        doc,
        "Figure 4.",
        figs / "figure_5_pair_core_offsets.png",
        "Figure 4. Frozen turn-change + density-scale pair across five window phases, generated directly from B50.12 outputs. "
        "The dotted line is the predeclared -0.04 nominal amplitude floor."
    )
    insert_figure_before_heading(
        doc,
        "10. Empirical conjecture suggested by the experiments",
        figs / "figure_6_full_vs_pair_offsets.png",
        "Figure 5. Full five-channel composite and frozen turn+density pair across offset phases, generated directly from frozen B50.6–B50.12 outputs."
    )

    # Full-score offset table.
    full = pd.read_csv(tabs / "table_full_score_offsets.csv")
    full = full[full["offset"] != 0].sort_values("offset")
    t = table_by_headers(doc, ["Offset","Full-score effect","Interpretation"])
    rows = []
    for _,r in full.iterrows():
        eff = float(r["full_score_effect"])
        interp = "negative; weaker amplitude" if abs(eff) < 0.04 else "negative; nominal-amplitude region"
        if int(r["offset"]) == 75:
            interp = "external-offset replication reference"
        rows.append([f"+{int(r['offset'])}", fmt(eff,5), interp])
    rewrite_rows(t, rows)

    # Channel decomposition.
    ch = pd.read_csv(tabs / "table_channel_decomposition.csv")
    t = table_by_headers(doc, ["Channel","Effect","Holm p","Confirmed"])
    rows = []
    for _,r in ch.iterrows():
        conf = bool(r.get("channel_confirmed", False))
        note = "Yes" if conf else "No: frozen effect-size gate fails"
        rows.append([
            str(r["channel"]).replace("_"," "),
            fmt(r["observed_mean_effect"],5),
            fmt(r.get("holm_p_two_sided", float("nan")),4),
            note,
        ])
    rewrite_rows(t, rows)

    # Pair-core offset table.
    p12 = pd.read_csv(tabs / "table_pair_core_offsets.csv").sort_values("offset")
    t = table_by_headers(doc, ["Offset","Pair effect","Holm p","Negative-config frac.","Nominal thirds","Frozen gate"])
    rows = []
    for _,r in p12.iterrows():
        gate = "PASS" if bool(r.get("nominal_offset_replication", False)) and bool(r.get("thirds_pass", False)) else "Amplitude/thirds fail"
        rows.append([
            f"+{int(r['offset'])}",
            fmt(r["effect"],6),
            fmt(r["holm_p_lower"],3),
            fmt(r["negative_config_fraction"],3),
            f"{int(r['nominal_thirds'])}/3",
            gate,
        ])
    rewrite_rows(t, rows)

    # Code/data availability statement.
    avail = (args.assets_dir / "release" / "CODE_DATA_AVAILABILITY.md").read_text(encoding="utf-8")
    body = "\n".join(
        line for line in avail.splitlines()
        if not line.startswith("#") and line.strip()
    )
    for p in doc.paragraphs:
        if p.text.startswith("Code and data availability statement"):
            replace_text(p, "Code and data availability. " + body)
            break

    # Reproducibility section: add machine-generation statement.
    h12 = next(p for p in doc.paragraphs if p.text.strip() == "12. Reproducibility and release package")
    inserted = doc.add_paragraph(
        "PUB-003 generation contract. Every numerical result table and data-derived figure in the submission version is generated "
        "programmatically from frozen B50.6–B50.12 CSV/JSON artifacts. The release contains the generation script, the exact input "
        "hash manifest, publication-number JSON, machine-generated CSV tables, 300-dpi PNG figures, vector PDF figures, and SHA-256 checksums."
    )
    h12._p.addnext(inserted._p)

    # Completion-note cleanup and status.
    for pp in doc.paragraphs:
        if pp.text.startswith("Generate final figures directly from archived CSV/JSON outputs"):
            replace_text(
                pp,
                "PUB-003 figure/table generation is now machine-derived directly from the frozen CSV/JSON outputs."
            )

    comp = next(p for p in doc.paragraphs if p.text.startswith("Submission completion notes"))
    note = doc.add_paragraph(
        "PUB-003 local asset generation and manuscript patch completed. Final shipping gate: render this DOCX, visually inspect every page, "
        "then perform journal-language/metadata finalization."
    )
    note.style = "List Bullet"
    comp._p.addnext(note._p)

    # Footer.
    for sec in doc.sections:
        for p in sec.footer.paragraphs:
            if "v0.4" in p.text:
                for r in p.runs:
                    r.text = r.text.replace("v0.4 / PUB-002", "v0.5 / PUB-003").replace("v0.4","v0.5 / PUB-003")

    args.manuscript_out.parent.mkdir(parents=True, exist_ok=True)
    doc.save(args.manuscript_out)
    print("PUB-003 manuscript patched:", args.manuscript_out)


if __name__ == "__main__":
    main()
