#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
TDC TOR A / B50.9 — Independent-Corpus Replication
==================================================

Purpose
-------
B50.6 established matched physical-adjacency specificity on the original
physical sequence. B50.7 replicated the frozen negative effect on +75 offset
windows. B50.8 showed same-corpus multi-offset phase robustness. B50.9 moves
the test onto a SOURCE-DISJOINT prime segment corpus that has not been used by
B50.6, B50.7, or B50.8.

The scientific question is frozen:

    Does the physical next state remain systematically LOWER in the frozen
    continuous-front percentile than full-operator-distance-matched,
    non-adjacent destinations on a source-disjoint corpus?

Frozen target
-------------
    mean physical percentile effect = mean(percentile) - 0.5 < 0

Confirmatory primary gate
-------------------------
    observed mean effect <= -0.05
    matched-set identity p_lower <= 0.01

Representation convergence
--------------------------
    >= 80% of frozen B50.4 configurations have negative mean effect

Thirds robustness
-----------------
    3/3 contiguous thirds have negative effect
    >= 2/3 thirds have:
        effect <= -0.04
        p_lower <= 0.05

Independent-corpus semantics
----------------------------
B50.9 defines "independent corpus" operationally as SOURCE-DISJOINT from all
prime segment files exposed to the B50.6-B50.8 lineage:

  1. original B50 state windows from --state-dataset,
  2. B50.7 +75 offset-window plan from --b50-7-dir,
  3. every B50.8 offset subrun plan found under --b50-8-dir.

The B50.9 plan selects the EARLIEST contiguous run of segment IDs in
--independent-prime-root that is completely disjoint from that prior exposure.
The default confirmatory design requires exactly 666 windows, using the frozen
training window length and physical start step inferred from the original state
sequence. With the current 200/150 geometry this requires 99,950 consecutive
new source segments.

This is a data-partition replication. If the new files are generated by the
same prime-generation pipeline, it is source-disjoint but not an independently
generated mathematical universe. The report states that boundary explicitly.

Frozen representation
---------------------
- Markov operator construction: exact frozen B50 implementation.
- operator dimension: must equal original training stack dimension.
- PCA mean/basis: fit ONLY on original B50.2 operator stack.
- independent operators: projected into frozen training PCA basis.
- B50.4 dimensions / graph-k / diffusion-mode count: frozen protocol.
- front-channel robust scaling: frozen from ORIGINAL B50.4 front features.
- matched controls: 20 non-adjacent destinations, min index separation 10.
- full operator-space distance matching: frozen B50.6/B50.7 semantics.

Modes
-----
plan
    Build the prior-exposure inventory, scan the independent source root,
    freeze the earliest eligible source-disjoint 666-window plan, and write
    provenance manifests. Does not parse prime values.

extract
    Reconstruct operators for the frozen independent-corpus plan. Resumable
    per-window cache, atomic checkpoints, hardlink-only temporary staging.

 audit
    Run the frozen independent-corpus adjacency replication.

all
    plan + extract + audit.

Important stop rule
-------------------
If the available prime files do not contain a contiguous, fully source-disjoint
run long enough for the frozen 666-window design, PLAN is written with PASS=False
and verdict INSUFFICIENT_DISJOINT_CORPUS. Do not shrink the corpus after seeing
that result and still call the run confirmatory. A custom --target-windows is
allowed for engineering/smoke work only and is marked protocol-modified.

No B59/B59.1/B59.2 quantity is read or used.
No individual-prime prediction, RH, or theorem claim is made.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import math
import os
import re
import shutil
import time
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Set, Tuple

import numpy as np
import pandas as pd

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt


VERSION = "B50.9_independent_corpus_replication_v1"
FROZEN_TARGET_WINDOWS = 666
FROZEN_CONTROLS = 20
FROZEN_MIN_INDEX_SEPARATION = 10
FROZEN_RANDOMIZATION_REPLICATES = 5000
FROZEN_GAP_BINS = 64
FROZEN_SEED = 50909

THRESHOLDS = {
    "matching_median_abs_log_distance_error_max": 0.10,
    "matching_q90_abs_log_distance_error_max": 0.25,
    "primary_effect_max": -0.05,
    "primary_p_lower_max": 0.01,
    "config_negative_fraction_min": 0.80,
    "third_effect_max": -0.04,
    "third_p_lower_max": 0.05,
    "third_negative_required": 3,
    "third_nominal_required": 2,
}

SEGMENT_RE = re.compile(r"primes_batch_(\d+)_all_with_1\.txt$", re.IGNORECASE)


# ---------------------------------------------------------------------------
# Generic utilities
# ---------------------------------------------------------------------------


def now_s() -> str:
    return time.strftime("%Y-%m-%d %H:%M:%S")


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def atomic_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(path)


def atomic_json(path: Path, obj: Any) -> None:
    atomic_text(path, json.dumps(obj, ensure_ascii=False, indent=2, allow_nan=True))


def atomic_csv(path: Path, df: pd.DataFrame) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    df.to_csv(tmp, index=False)
    tmp.replace(path)


def atomic_npz(path: Path, **kwargs) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp.npz")
    np.savez_compressed(tmp, **kwargs)
    tmp.replace(path)


def import_module(path: Path, name: str):
    if not path.exists():
        raise FileNotFoundError(path)
    spec = importlib.util.spec_from_file_location(name, str(path))
    if spec is None or spec.loader is None:
        raise ImportError(path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def import_b507(path: Path):
    mod = import_module(path, "tdc_b507_frozen_b509")
    required = [
        "parse_range_name",
        "import_b50",
        "import_b504",
        "compute_operator_for_window",
        "cache_path",
        "save_cache",
        "load_cache",
        "frozen_pca_basis",
        "projection_parity",
        "build_external_configs",
        "external_raw_parity_audit",
        "build_matched_controls",
        "build_replication_cube",
        "matched_identity_null_lower",
    ]
    missing = [x for x in required if not hasattr(mod, x)]
    if missing:
        raise AttributeError(f"B50.7 missing required frozen API: {missing}")
    return mod


def expand_interval(a: int, b: int) -> Iterable[int]:
    return range(int(a), int(b) + 1)


def interval_set_from_dataframe(df: pd.DataFrame, start_col: str, end_col: str) -> Set[int]:
    out: Set[int] = set()
    for _, r in df.iterrows():
        out.update(expand_interval(int(r[start_col]), int(r[end_col])))
    return out


def protocol_modified(args) -> bool:
    return bool(
        args.target_windows != FROZEN_TARGET_WINDOWS
        or args.controls_per_transition != FROZEN_CONTROLS
        or args.min_index_separation != FROZEN_MIN_INDEX_SEPARATION
        or args.randomization_replicates != FROZEN_RANDOMIZATION_REPLICATES
        or args.gap_bins != FROZEN_GAP_BINS
        or args.seed != FROZEN_SEED
        or args.independent_start_segment is not None
    )


# ---------------------------------------------------------------------------
# Frozen lineage and prior source exposure
# ---------------------------------------------------------------------------


def validate_lineage(args) -> Dict[str, Any]:
    p6 = Path(args.b50_6_summary)
    p7 = Path(args.b50_7_dir) / "b50_7_summary.json"
    p8 = Path(args.b50_8_dir) / "b50_8_summary.json"
    for p in (p6, p7, p8):
        if not p.exists():
            raise FileNotFoundError(p)

    s6 = json.loads(p6.read_text(encoding="utf-8"))
    s7 = json.loads(p7.read_text(encoding="utf-8"))
    s8 = json.loads(p8.read_text(encoding="utf-8"))

    v6 = s6.get("final_verdict") == "PHYSICAL_ADJACENCY_SPECIFICITY_REPLICATED"
    v7 = s7.get("final_verdict") == "EXTERNAL_OFFSET_ADJACENCY_SPECIFICITY_REPLICATED"
    v8 = s8.get("final_verdict") == "MULTI_OFFSET_PHASE_ROBUST_EFFECT_INVARIANCE"

    e6 = float(s6.get("primary_specificity", {}).get("observed_mean_effect", float("nan")))
    e7 = float(s7.get("primary_replication", {}).get("observed_mean_effect", float("nan")))
    e8_mean = float(s8.get("effect_invariance", {}).get("new_offsets_mean_effect", float("nan")))
    e8_med = float(s8.get("effect_invariance", {}).get("new_offsets_median_effect", float("nan")))

    effects_negative = bool(
        np.isfinite(e6) and np.isfinite(e7) and np.isfinite(e8_mean)
        and e6 < 0 and e7 < 0 and e8_mean < 0
    )

    return {
        "b50_6_verdict": s6.get("final_verdict"),
        "b50_7_verdict": s7.get("final_verdict"),
        "b50_8_verdict": s8.get("final_verdict"),
        "b50_6_effect": e6,
        "b50_7_effect": e7,
        "b50_8_mean_effect": e8_mean,
        "b50_8_median_effect": e8_med,
        "verdicts_ok": bool(v6 and v7 and v8),
        "negative_reference_direction_ok": effects_negative,
        "pass": bool(v6 and v7 and v8 and effects_negative),
        "source_hashes": {
            "b50_6_summary": sha256_file(p6),
            "b50_7_summary": sha256_file(p7),
            "b50_8_summary": sha256_file(p8),
        },
    }


def original_geometry(b507, state: pd.DataFrame) -> Dict[str, Any]:
    ranges = [b507.parse_range_name(x) for x in state["range_name"].astype(str)]
    starts = np.asarray([a for a, _ in ranges], dtype=int)
    ends = np.asarray([b for _, b in ranges], dtype=int)
    lengths = ends - starts + 1
    steps = np.diff(starts)

    step_vals, step_counts = np.unique(steps, return_counts=True)
    len_vals, len_counts = np.unique(lengths, return_counts=True)
    step_i = int(np.argmax(step_counts))
    len_i = int(np.argmax(len_counts))
    step = int(step_vals[step_i])
    length = int(len_vals[len_i])
    step_frac = float(step_counts[step_i] / len(steps))
    length_frac = float(len_counts[len_i] / len(lengths))

    if step_frac < 0.95 or length_frac < 0.95:
        raise RuntimeError(
            f"Original geometry is not sufficiently uniform: step fraction={step_frac}, length fraction={length_frac}"
        )

    return {
        "ranges": ranges,
        "nominal_step": step,
        "nominal_length": length,
        "step_mode_fraction": step_frac,
        "length_mode_fraction": length_frac,
    }


def collect_prior_exposure(args, b507, state: pd.DataFrame) -> Tuple[Set[int], pd.DataFrame, Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    exposed: Set[int] = set()

    # Original B50 sequence.
    for idx, name in enumerate(state["range_name"].astype(str)):
        a, b = b507.parse_range_name(name)
        exposed.update(expand_interval(a, b))
        rows.append({
            "source_family": "B50_original",
            "source_file": str(Path(args.state_dataset)),
            "range_index": idx,
            "range_name": name,
            "start_segment": a,
            "end_segment": b,
        })

    # B50.7 +75 plan.
    p7 = Path(args.b50_7_dir) / "b50_7_offset_window_plan.csv"
    if not p7.exists():
        raise FileNotFoundError(p7)
    d7 = pd.read_csv(p7)
    for _, r in d7.iterrows():
        a, b = int(r["start_segment"]), int(r["end_segment"])
        exposed.update(expand_interval(a, b))
        rows.append({
            "source_family": "B50.7_plus75",
            "source_file": str(p7),
            "range_index": int(r.get("offset_range_index", len(rows))),
            "range_name": str(r["range_name"]),
            "start_segment": a,
            "end_segment": b,
        })

    # Every B50.8 offset subrun plan.
    b508_root = Path(args.b50_8_dir)
    plan_files = sorted(b508_root.glob("offset_*/b50_7_offset_window_plan.csv"))
    if len(plan_files) < 4:
        raise RuntimeError(
            f"Expected at least 4 B50.8 offset subrun plans under {b508_root}; found {len(plan_files)}"
        )
    for pf in plan_files:
        df = pd.read_csv(pf)
        family = f"B50.8_{pf.parent.name}"
        for _, r in df.iterrows():
            a, b = int(r["start_segment"]), int(r["end_segment"])
            exposed.update(expand_interval(a, b))
            rows.append({
                "source_family": family,
                "source_file": str(pf),
                "range_index": int(r.get("offset_range_index", len(rows))),
                "range_name": str(r["range_name"]),
                "start_segment": a,
                "end_segment": b,
            })

    exposure_df = pd.DataFrame(rows)
    if not exposed:
        raise RuntimeError("Prior exposure set is empty")

    exposure_summary = {
        "prior_exposed_segment_count": int(len(exposed)),
        "prior_exposed_min_segment": int(min(exposed)),
        "prior_exposed_max_segment": int(max(exposed)),
        "b50_8_subrun_plan_count": int(len(plan_files)),
        "source_families": sorted(exposure_df["source_family"].unique().tolist()),
    }
    return exposed, exposure_df, exposure_summary


# ---------------------------------------------------------------------------
# Independent source inventory and plan
# ---------------------------------------------------------------------------


def scan_segment_files(root: Path) -> pd.DataFrame:
    if not root.exists():
        raise FileNotFoundError(root)
    rows = []
    for p in root.glob("primes_batch_*_all_with_1.txt"):
        m = SEGMENT_RE.search(p.name)
        if not m:
            continue
        st = p.stat()
        rows.append({
            "segment_index": int(m.group(1)),
            "file_name": p.name,
            "path": str(p),
            "size_bytes": int(st.st_size),
            "mtime_ns": int(st.st_mtime_ns),
        })
    if not rows:
        raise RuntimeError(f"No prime segment files found in {root}")
    df = pd.DataFrame(rows).sort_values("segment_index", kind="stable").reset_index(drop=True)
    if df["segment_index"].duplicated().any():
        dup = df[df["segment_index"].duplicated(keep=False)]["segment_index"].tolist()[:10]
        raise RuntimeError(f"Duplicate segment IDs in independent root: {dup}")
    return df


def contiguous_runs(ids: Sequence[int]) -> List[Tuple[int, int, int]]:
    arr = np.asarray(sorted(set(int(x) for x in ids)), dtype=int)
    if len(arr) == 0:
        return []
    runs = []
    a = prev = int(arr[0])
    for x in arr[1:]:
        x = int(x)
        if x != prev + 1:
            runs.append((a, prev, prev - a + 1))
            a = x
        prev = x
    runs.append((a, prev, prev - a + 1))
    return runs


def choose_independent_run(
    available_ids: Sequence[int],
    exposed: Set[int],
    required_span: int,
    requested_start: Optional[int],
) -> Tuple[Optional[int], List[Tuple[int, int, int]], Dict[str, Any]]:
    eligible = [int(x) for x in available_ids if int(x) not in exposed]
    runs = contiguous_runs(eligible)
    qualified = [r for r in runs if r[2] >= required_span]

    if requested_start is not None:
        start = int(requested_start)
        end = start + required_span - 1
        ok = any(start >= a and end <= b for a, b, _ in runs)
        chosen = start if ok else None
    else:
        chosen = min((a for a, b, n in qualified), default=None)

    diag = {
        "eligible_segment_count": int(len(eligible)),
        "eligible_run_count": int(len(runs)),
        "qualified_run_count": int(len(qualified)),
        "required_contiguous_span": int(required_span),
        "requested_start": requested_start,
        "chosen_start": chosen,
        "longest_eligible_run": int(max((r[2] for r in runs), default=0)),
        "runs_preview": [
            {"start": int(a), "end": int(b), "length": int(n)}
            for a, b, n in runs[:20]
        ],
    }
    return chosen, runs, diag


def build_independent_plan(
    start: int,
    target_windows: int,
    step: int,
    length: int,
) -> pd.DataFrame:
    rows = []
    for i in range(target_windows):
        a = int(start + i * step)
        b = int(a + length - 1)
        rows.append({
            "range_index": i,
            "range_name": f"range_{a:06d}-{b:06d}",
            "start_segment": a,
            "end_segment": b,
            "window_length": length,
            "start_step": step if i > 0 else 0,
        })
    return pd.DataFrame(rows)


def metadata_manifest_hash(inv: pd.DataFrame) -> str:
    cols = ["segment_index", "file_name", "size_bytes", "mtime_ns"]
    text = "\n".join(
        "|".join(str(r[c]) for c in cols)
        for _, r in inv.sort_values("segment_index").iterrows()
    )
    return sha256_text(text)


def plan_mode(args, b507) -> Dict[str, Any]:
    out = Path(args.output_dir)
    out.mkdir(parents=True, exist_ok=True)

    lineage = validate_lineage(args)
    state = pd.read_csv(args.state_dataset)
    b507.validate_state_dataset(state)
    geom = original_geometry(b507, state)
    exposed, exposure_df, exposure_summary = collect_prior_exposure(args, b507, state)
    inv = scan_segment_files(Path(args.independent_prime_root))

    required_span = int(geom["nominal_length"] + (args.target_windows - 1) * geom["nominal_step"])
    chosen_start, runs, run_diag = choose_independent_run(
        inv["segment_index"].to_numpy(int),
        exposed,
        required_span,
        args.independent_start_segment,
    )

    inv = inv.copy()
    inv["used_in_prior_b50_lineage"] = inv["segment_index"].isin(exposed)

    if chosen_start is None:
        plan = pd.DataFrame(columns=[
            "range_index", "range_name", "start_segment", "end_segment", "window_length", "start_step"
        ])
        plan_segment_set: Set[int] = set()
        all_files_present = False
        disjoint = False
    else:
        plan = build_independent_plan(
            chosen_start,
            args.target_windows,
            int(geom["nominal_step"]),
            int(geom["nominal_length"]),
        )
        plan_segment_set = set(range(
            int(plan["start_segment"].min()),
            int(plan["end_segment"].max()) + 1,
        ))
        available = set(inv["segment_index"].astype(int).tolist())
        all_files_present = plan_segment_set.issubset(available)
        disjoint = len(plan_segment_set & exposed) == 0

    inv["selected_for_b50_9"] = inv["segment_index"].isin(plan_segment_set)
    selected_inv = inv[inv["selected_for_b50_9"]].copy()

    exact_count = len(plan) == args.target_windows
    lengths_exact = bool(
        len(plan) > 0
        and np.all(plan["window_length"].to_numpy(int) == int(geom["nominal_length"]))
    )
    starts = plan["start_segment"].to_numpy(int) if len(plan) else np.array([], dtype=int)
    steps_exact = bool(
        len(starts) >= 2
        and np.all(np.diff(starts) == int(geom["nominal_step"]))
    )

    frozen_protocol_modified = protocol_modified(args)
    plan_pass = bool(
        lineage["pass"]
        and chosen_start is not None
        and exact_count
        and all_files_present
        and disjoint
        and lengths_exact
        and steps_exact
        and not frozen_protocol_modified
    )

    if chosen_start is None:
        plan_verdict = "INSUFFICIENT_DISJOINT_CORPUS"
        reason = (
            "No contiguous source-disjoint segment run is long enough for the frozen "
            f"{args.target_windows}-window design requiring {required_span} segments."
        )
    elif not lineage["pass"]:
        plan_verdict = "INVALID_REPRODUCTION"
        reason = "B50.6/B50.7/B50.8 lineage qualification failed."
    elif not disjoint:
        plan_verdict = "INVALID_CORPUS_DISJOINTNESS"
        reason = "Candidate independent corpus overlaps source segments exposed to B50.6-B50.8."
    elif not all_files_present:
        plan_verdict = "INCOMPLETE_INDEPENDENT_CORPUS"
        reason = "At least one source segment required by the frozen plan is missing."
    elif frozen_protocol_modified:
        plan_verdict = "PROTOCOL_MODIFIED_ENGINEERING_ONLY"
        reason = "One or more confirmatory defaults were modified; no confirmatory verdict is allowed."
    else:
        plan_verdict = "INDEPENDENT_CORPUS_PLAN_FROZEN"
        reason = "Earliest contiguous source-disjoint corpus satisfying the frozen 666-window geometry was found."

    atomic_csv(out / "b50_9_prior_exposure_windows.csv", exposure_df)
    atomic_csv(out / "b50_9_independent_source_inventory.csv", inv)
    atomic_csv(out / "b50_9_independent_window_plan.csv", plan)

    source_meta_hash = metadata_manifest_hash(selected_inv) if len(selected_inv) else None
    plan_summary = {
        "version": VERSION,
        "created": now_s(),
        "lineage": lineage,
        "training_geometry": {
            "window_count": int(len(state)),
            "nominal_step": int(geom["nominal_step"]),
            "nominal_length": int(geom["nominal_length"]),
            "step_mode_fraction": float(geom["step_mode_fraction"]),
            "length_mode_fraction": float(geom["length_mode_fraction"]),
        },
        "prior_exposure": exposure_summary,
        "independent_source": {
            "root": str(Path(args.independent_prime_root)),
            "available_segment_count": int(len(inv)),
            "available_min_segment": int(inv["segment_index"].min()),
            "available_max_segment": int(inv["segment_index"].max()),
            "required_contiguous_span": required_span,
            "chosen_start_segment": chosen_start,
            "chosen_end_segment": (
                int(chosen_start + required_span - 1) if chosen_start is not None else None
            ),
            "selected_source_segment_count": int(len(selected_inv)),
            "selected_source_metadata_sha256": source_meta_hash,
            "source_disjoint_from_all_prior_b50_exposure": bool(disjoint),
            "all_required_files_present": bool(all_files_present),
            "run_diagnostics": run_diag,
        },
        "frozen_protocol": {
            "target_windows": int(args.target_windows),
            "controls_per_transition": int(args.controls_per_transition),
            "min_index_separation": int(args.min_index_separation),
            "randomization_replicates": int(args.randomization_replicates),
            "gap_bins": int(args.gap_bins),
            "seed": int(args.seed),
            "protocol_modified": frozen_protocol_modified,
        },
        "plan_integrity": {
            "exact_window_count": bool(exact_count),
            "window_lengths_exact": bool(lengths_exact),
            "start_steps_exact": bool(steps_exact),
            "plan_pass": plan_pass,
        },
        "plan_verdict": plan_verdict,
        "reason": reason,
        "input_hashes": {
            "state_dataset": sha256_file(Path(args.state_dataset)),
            "training_operator_stack": sha256_file(Path(args.training_operator_stack)),
            "b50_script": sha256_file(Path(args.b50_script)),
            "b50_4_script": sha256_file(Path(args.b50_4_script)),
            "b50_4_protocol": sha256_file(Path(args.b50_4_protocol)),
            "b50_4_front_features": sha256_file(Path(args.b50_4_front_features)),
            "b50_7_script": sha256_file(Path(args.b50_7_script)),
        },
        "scientific_boundary": (
            "Source-disjoint data-partition replication relative to every segment exposed "
            "to B50.6-B50.8. If source files are produced by the same generator/pipeline, "
            "this is not an independently generated mathematical universe."
        ),
    }
    if len(plan):
        plan_summary["plan_csv_sha256"] = sha256_file(out / "b50_9_independent_window_plan.csv")
    atomic_json(out / "b50_9_plan_summary.json", plan_summary)

    print("=== B50.9 INDEPENDENT-CORPUS PLAN ===")
    print(f"prior exposed segments : {exposure_summary['prior_exposed_segment_count']}")
    print(f"available source files : {len(inv)}")
    print(f"required span          : {required_span}")
    print(f"target windows         : {args.target_windows}")
    print(f"window length / step   : {geom['nominal_length']} / {geom['nominal_step']}")
    print(f"chosen start           : {chosen_start}")
    print(f"longest eligible run   : {run_diag['longest_eligible_run']}")
    print(f"source disjoint        : {disjoint}")
    print(f"all files present      : {all_files_present}")
    print(f"protocol modified      : {frozen_protocol_modified}")
    print(f"PLAN PASS              : {plan_pass}")
    print(f"PLAN VERDICT           : {plan_verdict}")
    print(f"plan                    : {out / 'b50_9_independent_window_plan.csv'}")

    return plan_summary


# ---------------------------------------------------------------------------
# Operator extraction
# ---------------------------------------------------------------------------


def ensure_plan_pass(out: Path) -> Dict[str, Any]:
    p = out / "b50_9_plan_summary.json"
    if not p.exists():
        raise FileNotFoundError("Run --mode plan first")
    s = json.loads(p.read_text(encoding="utf-8"))
    if not bool(s.get("plan_integrity", {}).get("plan_pass", False)):
        raise RuntimeError(
            f"Frozen B50.9 plan did not pass: {s.get('plan_verdict')} — {s.get('reason')}"
        )
    return s


def extract_mode(args, b507) -> Dict[str, Any]:
    out = Path(args.output_dir)
    out.mkdir(parents=True, exist_ok=True)
    plan_summary = ensure_plan_pass(out)

    plan_path = out / "b50_9_independent_window_plan.csv"
    plan = pd.read_csv(plan_path)
    prime_root = Path(args.independent_prime_root)

    # Freeze source provenance between PLAN and EXTRACT. We intentionally hash
    # the complete selected-file metadata manifest (segment id, basename, size,
    # mtime_ns), not the multi-terabyte corpus bytes. This is a fast integrity
    # gate; final operator-stack bytes are SHA-256 hashed after extraction.
    current_inv = scan_segment_files(prime_root)
    plan_segments = set(range(
        int(plan["start_segment"].min()),
        int(plan["end_segment"].max()) + 1,
    ))
    current_selected = current_inv[current_inv["segment_index"].isin(plan_segments)].copy()
    current_source_meta_hash = metadata_manifest_hash(current_selected)
    frozen_source_meta_hash = plan_summary["independent_source"].get("selected_source_metadata_sha256")
    if len(current_selected) != len(plan_segments):
        raise RuntimeError(
            f"INVALID_SOURCE_MANIFEST: expected {len(plan_segments)} source segments, "
            f"found {len(current_selected)}"
        )
    if current_source_meta_hash != frozen_source_meta_hash:
        raise RuntimeError(
            "INVALID_SOURCE_MANIFEST: independent source metadata changed after PLAN. "
            "Re-run PLAN only if you intentionally want a new frozen experiment."
        )

    b50 = b507.import_b50(Path(args.b50_script))

    with np.load(args.training_operator_stack, allow_pickle=False) as z:
        P_train = np.asarray(z["P_stack"], dtype=np.float64)
    expected_dim = int(P_train.shape[1])

    cache_dir = out / "operator_cache"
    cache_dir.mkdir(parents=True, exist_ok=True)
    staging_root = Path(args.staging_dir) if args.staging_dir else out / "_staging_hardlinks"
    staging_root.mkdir(parents=True, exist_ok=True)

    vectors: List[np.ndarray] = []
    meta_rows: List[Dict[str, Any]] = []
    status_rows: List[Dict[str, Any]] = []
    t_all = time.time()

    print("=== B50.9 INDEPENDENT-CORPUS OPERATOR EXTRACTION ===")
    print(f"windows      : {len(plan)}")
    print(f"prime root   : {prime_root}")
    print(f"operator dim : {expected_dim}")
    print(f"reuse cache  : {args.reuse_existing}")
    print(f"staging      : {staging_root}")

    for i, row in plan.iterrows():
        name = str(row["range_name"])
        cp = b507.cache_path(cache_dir, name)
        t0 = time.time()

        if args.reuse_existing and cp.exists():
            rec = b507.load_cache(cp, name, args.gap_bins)
            source = "cache"
        else:
            try:
                rec = b507.compute_operator_for_window(
                    b50,
                    prime_root,
                    staging_root,
                    row,
                    args.gap_bins,
                )
            except OSError as exc:
                if getattr(exc, "winerror", None) in (17, 1314) or getattr(exc, "errno", None) in (18,):
                    raise RuntimeError(
                        "Hardlink staging failed. Keep independent prime data on the same Windows volume "
                        "as the B50.9 output/staging directory, or provide --staging-dir on that volume."
                    ) from exc
                raise
            b507.save_cache(cp, rec, args.gap_bins)
            source = "recomputed"

        if int(rec["operator_dim"]) != expected_dim:
            raise RuntimeError(
                f"Operator dimension mismatch at {name}: {rec['operator_dim']} != {expected_dim}"
            )
        if int(rec["start_segment"]) != int(row["start_segment"]) or int(rec["end_segment"]) != int(row["end_segment"]):
            raise RuntimeError(f"Range bounds mismatch at {name}")

        vectors.append(np.asarray(rec["operator_vector"], dtype=np.float64))
        meta_rows.append({
            "range_index": int(i),
            "range_name": name,
            "start_segment": int(rec["start_segment"]),
            "end_segment": int(rec["end_segment"]),
            "n_primes": int(rec["n_primes"]),
            "n_gaps": int(rec["n_gaps"]),
            "mean_log_gap": float(rec["mean_log_gap"]),
            "gap_mean": float(rec["gap_mean"]),
            "gap_std": float(rec["gap_std"]),
        })
        status_rows.append({
            "range_index": int(i),
            "range_name": name,
            "source": source,
            "operator_dim": int(rec["operator_dim"]),
            "n_primes": int(rec["n_primes"]),
            "n_gaps": int(rec["n_gaps"]),
            "elapsed_seconds": float(time.time() - t0),
            "cache_path": str(cp),
        })

        print(
            f"[{i+1:03d}/{len(plan):03d}] {name} {source} "
            f"time={status_rows[-1]['elapsed_seconds']:.1f}s",
            flush=True,
        )

        if args.checkpoint_every and (i + 1) % args.checkpoint_every == 0:
            atomic_csv(out / "b50_9_extraction_status.csv", pd.DataFrame(status_rows))
            atomic_json(out / "b50_9_extraction_checkpoint.json", {
                "version": VERSION,
                "updated": now_s(),
                "completed": int(i + 1),
                "total": int(len(plan)),
                "last_range": name,
                "elapsed_seconds": float(time.time() - t_all),
            })

    shutil.rmtree(staging_root, ignore_errors=True)

    P_ext = np.vstack(vectors)
    labels = np.asarray([r["range_name"] for r in meta_rows])
    expected_shape = (len(plan), expected_dim)
    if P_ext.shape != expected_shape:
        raise RuntimeError(f"Independent stack shape {P_ext.shape} != {expected_shape}")
    labels_exact = labels.tolist() == plan["range_name"].astype(str).tolist()
    if not labels_exact:
        raise RuntimeError("Independent stack labels/order differ from frozen plan")

    stack_path = out / "b50_9_independent_operator_stack.npz"
    atomic_npz(
        stack_path,
        P_stack=P_ext,
        labels=labels,
        gap_bins=np.asarray([args.gap_bins], dtype=np.int64),
    )
    atomic_csv(out / "b50_9_operator_metadata.csv", pd.DataFrame(meta_rows))
    atomic_csv(out / "b50_9_extraction_status.csv", pd.DataFrame(status_rows))

    manifest = {
        "version": VERSION,
        "created": now_s(),
        "independent_prime_root": str(prime_root),
        "plan_csv": str(plan_path),
        "plan_csv_sha256": sha256_file(plan_path),
        "plan_summary_sha256": sha256_file(out / "b50_9_plan_summary.json"),
        "training_operator_stack": str(Path(args.training_operator_stack)),
        "training_operator_stack_sha256": sha256_file(Path(args.training_operator_stack)),
        "b50_script": str(Path(args.b50_script)),
        "b50_script_sha256": sha256_file(Path(args.b50_script)),
        "range_count": int(P_ext.shape[0]),
        "operator_dim": int(P_ext.shape[1]),
        "stack_shape": list(P_ext.shape),
        "gap_bins": int(args.gap_bins),
        "labels_exact_against_plan": labels_exact,
        "source_disjointness_plan_pass": bool(
            plan_summary["independent_source"]["source_disjoint_from_all_prior_b50_exposure"]
        ),
        "source_metadata_manifest_sha256": current_source_meta_hash,
        "source_metadata_exact_against_plan": True,
        "hardlink_only_policy": True,
        "elapsed_seconds": float(time.time() - t_all),
        "stack_sha256": sha256_file(stack_path),
    }
    atomic_json(out / "b50_9_extraction_manifest.json", manifest)
    print(f"[B50.9] stack saved: {stack_path} shape={P_ext.shape}")
    return manifest


# ---------------------------------------------------------------------------
# Independent-corpus audit
# ---------------------------------------------------------------------------


def audit_mode(args, b507) -> Dict[str, Any]:
    out = Path(args.output_dir)
    out.mkdir(parents=True, exist_ok=True)
    plan_summary = ensure_plan_pass(out)

    required = {
        "plan_csv": out / "b50_9_independent_window_plan.csv",
        "plan_summary": out / "b50_9_plan_summary.json",
        "independent_stack": out / "b50_9_independent_operator_stack.npz",
        "extraction_manifest": out / "b50_9_extraction_manifest.json",
        "training_stack": Path(args.training_operator_stack),
        "b50_4_protocol": Path(args.b50_4_protocol),
        "b50_4_front_features": Path(args.b50_4_front_features),
        "b50_4_script": Path(args.b50_4_script),
        "b50_6_summary": Path(args.b50_6_summary),
        "b50_7_summary": Path(args.b50_7_dir) / "b50_7_summary.json",
        "b50_8_summary": Path(args.b50_8_dir) / "b50_8_summary.json",
    }
    for name, p in required.items():
        if not p.exists():
            raise FileNotFoundError(f"{name}: {p}")

    lineage = validate_lineage(args)
    if not lineage["pass"]:
        raise RuntimeError("INVALID_REPRODUCTION")

    frozen_hashes = plan_summary.get("input_hashes", {})
    current_hashes = {
        "state_dataset": sha256_file(Path(args.state_dataset)),
        "training_operator_stack": sha256_file(Path(args.training_operator_stack)),
        "b50_script": sha256_file(Path(args.b50_script)),
        "b50_4_script": sha256_file(Path(args.b50_4_script)),
        "b50_4_protocol": sha256_file(Path(args.b50_4_protocol)),
        "b50_4_front_features": sha256_file(Path(args.b50_4_front_features)),
        "b50_7_script": sha256_file(Path(args.b50_7_script)),
    }
    frozen_inputs_exact = frozen_hashes == current_hashes
    if not frozen_inputs_exact:
        summary = {
            "version": VERSION,
            "final_verdict": "INVALID_FROZEN_INPUTS",
            "frozen_hashes": frozen_hashes,
            "current_hashes": current_hashes,
        }
        atomic_json(out / "b50_9_summary.json", summary)
        atomic_text(out / "b50_9_verdict.txt", "FINAL VERDICT: INVALID_FROZEN_INPUTS\n")
        return summary

    extraction_manifest = json.loads(required["extraction_manifest"].read_text(encoding="utf-8"))
    plan = pd.read_csv(required["plan_csv"])
    p4 = json.loads(required["b50_4_protocol"].read_text(encoding="utf-8"))
    training_fronts = pd.read_csv(required["b50_4_front_features"])

    with np.load(required["training_stack"], allow_pickle=False) as z:
        P_train = np.asarray(z["P_stack"], dtype=np.float64)
        train_labels = [str(x) for x in z["labels"]]
    with np.load(required["independent_stack"], allow_pickle=False) as z:
        P_ext = np.asarray(z["P_stack"], dtype=np.float64)
        ext_labels = [str(x) for x in z["labels"]]

    labels_exact = ext_labels == plan["range_name"].astype(str).tolist()
    operator_dim_exact = P_ext.shape[1] == P_train.shape[1]
    extraction_exact = bool(extraction_manifest.get("labels_exact_against_plan", False))
    source_disjoint = bool(
        plan_summary.get("independent_source", {}).get(
            "source_disjoint_from_all_prior_b50_exposure", False
        )
    )
    exact_windows = len(P_ext) == FROZEN_TARGET_WINDOWS

    if not (labels_exact and operator_dim_exact and extraction_exact and source_disjoint and exact_windows):
        summary = {
            "version": VERSION,
            "final_verdict": "INVALID_EXTRACTION",
            "integrity": {
                "labels_exact": labels_exact,
                "operator_dim_exact": operator_dim_exact,
                "extraction_labels_exact": extraction_exact,
                "source_disjoint": source_disjoint,
                "exact_666_windows": exact_windows,
            },
        }
        atomic_json(out / "b50_9_summary.json", summary)
        atomic_text(out / "b50_9_verdict.txt", "FINAL VERDICT: INVALID_EXTRACTION\n")
        return summary

    if protocol_modified(args):
        summary = {
            "version": VERSION,
            "final_verdict": "PROTOCOL_MODIFIED_NO_CONFIRMATORY_VERDICT",
            "reason": "B50.9 audit was invoked with non-frozen scientific defaults.",
        }
        atomic_json(out / "b50_9_summary.json", summary)
        atomic_text(out / "b50_9_verdict.txt", "FINAL VERDICT: PROTOCOL_MODIFIED_NO_CONFIRMATORY_VERDICT\n")
        return summary

    dims = [int(x) for x in p4["dimensions"]]
    graph_k_values = [int(x) for x in p4["graph_k_values"]]
    diffusion_modes_n = int(p4["diffusion_modes"])

    print("=== TDC TOR A / B50.9: INDEPENDENT-CORPUS REPLICATION ===")
    print(f"training stack      : {P_train.shape}")
    print(f"independent stack   : {P_ext.shape}")
    print(f"source disjoint     : {source_disjoint}")
    print(f"B50.6 effect        : {lineage['b50_6_effect']:.9f}")
    print(f"B50.7 effect        : {lineage['b50_7_effect']:.9f}")
    print(f"B50.8 mean effect   : {lineage['b50_8_mean_effect']:.9f}")
    print(f"frozen dimensions   : {dims}")
    print(f"frozen graph k      : {graph_k_values}")
    print()

    protocol = {
        "version": VERSION,
        "created": now_s(),
        "outcome_blind_to_b59": True,
        "independent_source_data": True,
        "lineage": lineage,
        "source_disjointness": {
            "prior_exposed_segment_count": plan_summary["prior_exposure"]["prior_exposed_segment_count"],
            "independent_start": plan_summary["independent_source"]["chosen_start_segment"],
            "independent_end": plan_summary["independent_source"]["chosen_end_segment"],
            "source_disjoint": source_disjoint,
        },
        "representation": {
            "training_pca_basis_frozen_from_original_stack": True,
            "dimensions": dims,
            "graph_k_values": graph_k_values,
            "diffusion_modes": diffusion_modes_n,
            "front_scaling_frozen_from_original_b50_4": True,
        },
        "matching": {
            "controls_per_transition": args.controls_per_transition,
            "min_index_separation": args.min_index_separation,
            "geometry": "independent full 4096D operator Euclidean",
        },
        "randomization_replicates": args.randomization_replicates,
        "thresholds": THRESHOLDS,
        "seed": args.seed,
        "frozen_input_hashes_exact": frozen_inputs_exact,
        "scientific_boundary": (
            "Source-disjoint independent data-partition replication. New source segments were not exposed "
            "to B50.6-B50.8. No B59 endpoint, individual-prime prediction, RH, or theorem claim."
        ),
    }
    atomic_json(out / "b50_9_protocol_manifest.json", protocol)

    # 0. Frozen PCA parity on training representation.
    print("[0/6] Frozen training PCA basis", flush=True)
    train_mean, train_Vt, train_scores = b507.frozen_pca_basis(P_train)
    pca_parity = b507.projection_parity(P_train, train_mean, train_Vt, train_scores, dims)
    atomic_json(out / "b50_9_frozen_pca_parity.json", pca_parity)
    print(f"      PCA parity PASS: {pca_parity['pass']}")
    if not pca_parity["pass"]:
        summary = {
            "version": VERSION,
            "final_verdict": "INVALID_REPRODUCTION",
            "reason": "Frozen PCA projection parity failed on original training stack.",
            "pca_parity": pca_parity,
        }
        atomic_json(out / "b50_9_summary.json", summary)
        atomic_text(out / "b50_9_verdict.txt", "FINAL VERDICT: INVALID_REPRODUCTION\n")
        return summary

    # 1. Independent configs using frozen training PCA basis.
    print("[1/6] Projecting independent corpus into frozen representation", flush=True)
    b504, front_fn = b507.import_b504(required["b50_4_script"])
    configs = b507.build_external_configs(
        b504,
        P_ext,
        train_mean,
        train_Vt,
        dims,
        graph_k_values,
        diffusion_modes_n,
    )
    sample_sources = np.linspace(1, len(P_ext) - 2, min(7, len(P_ext) - 2), dtype=int).tolist()
    parity_ok, parity_df = b507.external_raw_parity_audit(front_fn, configs, sample_sources)
    atomic_csv(out / "b50_9_independent_raw_feature_parity.csv", parity_df)
    print(f"      raw-feature parity PASS: {parity_ok}")
    if not parity_ok:
        summary = {
            "version": VERSION,
            "final_verdict": "INVALID_REPRODUCTION",
            "reason": "Independent raw front-feature parity against frozen B50.4 failed.",
        }
        atomic_json(out / "b50_9_summary.json", summary)
        atomic_text(out / "b50_9_verdict.txt", "FINAL VERDICT: INVALID_REPRODUCTION\n")
        return summary

    # 2. Matched controls on independent full operator geometry.
    print("[2/6] Independent-corpus full-operator matched controls", flush=True)
    cmap, matching_df = b507.build_matched_controls(
        P_ext,
        args.controls_per_transition,
        args.min_index_separation,
    )
    atomic_csv(out / "b50_9_matching_audit.csv", matching_df)
    matching_median = float(matching_df["abs_log_distance_error"].median())
    matching_q90 = float(matching_df["abs_log_distance_error"].quantile(0.90))
    matching_pass = bool(
        matching_median <= THRESHOLDS["matching_median_abs_log_distance_error_max"]
        and matching_q90 <= THRESHOLDS["matching_q90_abs_log_distance_error_max"]
    )
    print(f"      match median={matching_median:.6f} q90={matching_q90:.6f} PASS={matching_pass}")
    if not matching_pass:
        summary = {
            "version": VERSION,
            "final_verdict": "INVALID_MATCHING_GEOMETRY",
            "matching": {
                "median_abs_log_distance_error": matching_median,
                "q90_abs_log_distance_error": matching_q90,
                "pass": False,
            },
        }
        atomic_json(out / "b50_9_summary.json", summary)
        atomic_text(out / "b50_9_verdict.txt", "FINAL VERDICT: INVALID_MATCHING_GEOMETRY\n")
        return summary

    # 3. Frozen front scoring.
    print("[3/6] Frozen front scoring on independent corpus", flush=True)
    tis, cids, pct, score, cfg_df = b507.build_replication_cube(
        configs,
        training_fronts,
        cmap,
    )
    consensus = np.median(pct, axis=1)
    physical_pct = consensus[:, 0]

    transition_rows = []
    for ti, i in enumerate(tis):
        transition_rows.append({
            "transition_index": i,
            "from_range": ext_labels[i],
            "to_range": ext_labels[i + 1],
            "consensus_physical_percentile": float(physical_pct[ti]),
            "consensus_percentile_effect": float(physical_pct[ti] - 0.5),
            "median_physical_front_score": float(np.median(score[ti, :, 0])),
            "median_control_front_score": float(np.median(score[ti, :, 1:])),
            "control_dest_indices": ",".join(str(int(x)) for x in cmap[i]),
        })
    transition_df = pd.DataFrame(transition_rows)
    atomic_csv(out / "b50_9_transition_specificity.csv", transition_df)

    negative_fraction = float(np.mean(cfg_df["mean_percentile_effect"].to_numpy(float) < 0.0))
    config_pass = bool(negative_fraction >= THRESHOLDS["config_negative_fraction_min"])
    cfg_df["negative_effect"] = cfg_df["mean_percentile_effect"] < 0.0
    atomic_csv(out / "b50_9_config_specificity.csv", cfg_df)

    # 4. Primary directional matched identity null.
    print("[4/6] Directional matched-set identity randomization", flush=True)
    primary, null = b507.matched_identity_null_lower(
        consensus,
        args.randomization_replicates,
        args.seed + 1000,
    )
    primary_pass = bool(
        primary["observed_mean_effect"] <= THRESHOLDS["primary_effect_max"]
        and primary["p_lower"] <= THRESHOLDS["primary_p_lower_max"]
    )
    primary["pass"] = primary_pass
    primary["b50_6_reference_effect"] = lineage["b50_6_effect"]
    primary["b50_7_reference_effect"] = lineage["b50_7_effect"]
    primary["b50_8_reference_mean_effect"] = lineage["b50_8_mean_effect"]
    atomic_csv(out / "b50_9_primary_null.csv", pd.DataFrame({
        "replicate": np.arange(len(null)),
        "mean_percentile_effect": null,
    }))

    # 5. Contiguous thirds.
    print("[5/6] Independent-corpus thirds robustness", flush=True)
    n_t = len(tis)
    edges = np.linspace(0, n_t, 4, dtype=int)
    thirds_rows = []
    negative_count = 0
    nominal_count = 0
    for third in range(3):
        mask = np.zeros(n_t, dtype=bool)
        mask[edges[third]:edges[third + 1]] = True
        res, _ = b507.matched_identity_null_lower(
            consensus,
            args.randomization_replicates,
            args.seed + 2000 + third,
            mask=mask,
        )
        neg = bool(res["observed_mean_effect"] < 0.0)
        nominal = bool(
            res["observed_mean_effect"] <= THRESHOLDS["third_effect_max"]
            and res["p_lower"] <= THRESHOLDS["third_p_lower_max"]
        )
        negative_count += int(neg)
        nominal_count += int(nominal)
        idxs = np.asarray(tis)[mask]
        thirds_rows.append({
            "third": third + 1,
            "transition_count": int(mask.sum()),
            "first_transition_index": int(idxs[0]),
            "last_transition_index": int(idxs[-1]),
            **res,
            "negative_direction": neg,
            "nominal_replication_pass": nominal,
        })
    thirds_df = pd.DataFrame(thirds_rows)
    atomic_csv(out / "b50_9_replication_thirds.csv", thirds_df)
    thirds_pass = bool(
        negative_count >= THRESHOLDS["third_negative_required"]
        and nominal_count >= THRESHOLDS["third_nominal_required"]
    )

    # 6. Frozen verdict.
    print("[6/6] Frozen independent-corpus verdict", flush=True)
    effect = float(primary["observed_mean_effect"])
    if primary_pass and config_pass and thirds_pass:
        verdict = "INDEPENDENT_CORPUS_ADJACENCY_SPECIFICITY_REPLICATED"
        reason = (
            "The frozen negative physical-adjacency effect replicates on a source-disjoint corpus, "
            "passes matched identity randomization, converges across frozen representations, and "
            "is robust across all three contiguous independent-corpus thirds."
        )
    elif primary_pass and config_pass and not thirds_pass:
        verdict = "INDEPENDENT_CORPUS_SIGNAL_WITH_WEAK_THIRDS"
        reason = (
            "The full source-disjoint corpus and frozen representation-convergence gates pass, "
            "but the pre-declared thirds robustness gate does not fully pass."
        )
    elif effect >= 0.05:
        verdict = "INDEPENDENT_CORPUS_DIRECTION_REVERSED"
        reason = (
            "The source-disjoint corpus shows a materially positive effect, opposite to the frozen "
            "negative B50.6-B50.8 direction."
        )
    elif (not primary_pass) and abs(effect) < 0.05:
        verdict = "INDEPENDENT_CORPUS_NULL_COMPATIBLE"
        reason = (
            "The source-disjoint corpus does not show a sufficiently large negative physical-adjacency "
            "effect under the frozen primary replication contract."
        )
    else:
        verdict = "WEAK_OR_INCONSISTENT_INDEPENDENT_CORPUS_REPLICATION"
        reason = (
            "The source-disjoint replication is mixed under the frozen effect-size, directional null, "
            "representation-convergence, and thirds gates."
        )

    summary = {
        "version": VERSION,
        "finished": now_s(),
        "outcome_blind_to_b59": True,
        "source_disjoint_independent_corpus": True,
        "integrity": {
            "frozen_inputs_exact": frozen_inputs_exact,
            "source_disjoint": source_disjoint,
            "labels_exact": labels_exact,
            "operator_dim_exact": operator_dim_exact,
            "exact_666_windows": exact_windows,
            "frozen_pca_projection_parity": pca_parity,
            "independent_raw_feature_parity_ok": parity_ok,
        },
        "lineage": lineage,
        "independent_sequence": {
            "window_count": int(len(P_ext)),
            "transition_sources_used": int(len(tis)),
            "start_segment": int(plan["start_segment"].min()),
            "end_segment": int(plan["end_segment"].max()),
            "window_length": int(plan_summary["training_geometry"]["nominal_length"]),
            "start_step": int(plan_summary["training_geometry"]["nominal_step"]),
            "prior_exposed_segment_count": int(plan_summary["prior_exposure"]["prior_exposed_segment_count"]),
        },
        "matching": {
            "controls_per_transition": args.controls_per_transition,
            "min_index_separation": args.min_index_separation,
            "median_abs_log_distance_error": matching_median,
            "q90_abs_log_distance_error": matching_q90,
            "pass": matching_pass,
        },
        "primary_replication": primary,
        "config_convergence": {
            "negative_effect_fraction": negative_fraction,
            "pass": config_pass,
        },
        "thirds_robustness": {
            "negative_thirds": negative_count,
            "nominally_replicated_thirds": nominal_count,
            "pass": thirds_pass,
            "rows": thirds_df.to_dict(orient="records"),
        },
        "thresholds": THRESHOLDS,
        "final_verdict": verdict,
        "final_reason": reason,
        "scientific_boundary": (
            "Source-disjoint data-partition replication relative to all B50.6-B50.8 source exposure. "
            "If produced by the same generator, it is not an independently generated mathematical universe. "
            "No B59 validation, individual-prime prediction, RH, or theorem claim."
        ),
    }
    atomic_json(out / "b50_9_summary.json", summary)

    # Plots.
    plt.figure(figsize=(8, 5))
    plt.hist(null, bins=45)
    plt.axvline(effect, linewidth=2)
    plt.xlabel("mean percentile effect under matched-set identity null")
    plt.ylabel("count")
    plt.title("B50.9 source-disjoint corpus matched identity null")
    plt.tight_layout()
    plt.savefig(out / "b50_9_primary_null.png", dpi=160)
    plt.close()

    plt.figure(figsize=(11, 5))
    plt.plot(
        transition_df["transition_index"],
        transition_df["consensus_physical_percentile"],
        linewidth=1,
    )
    plt.axhline(0.5, linestyle="--", linewidth=0.8)
    plt.ylim(-0.02, 1.02)
    plt.xlabel("independent-corpus physical transition index")
    plt.ylabel("physical destination percentile")
    plt.title("B50.9 independent-corpus adjacency specificity")
    plt.grid(True)
    plt.tight_layout()
    plt.savefig(out / "b50_9_specificity_by_transition.png", dpi=160)
    plt.close()

    plt.figure(figsize=(9, 5))
    x = np.arange(len(cfg_df))
    plt.plot(x, cfg_df["mean_physical_percentile"], marker="o")
    plt.axhline(0.5, linestyle="--", linewidth=0.8)
    plt.xticks(x, cfg_df["config_id"], rotation=60, ha="right")
    plt.ylabel("mean physical percentile")
    plt.title("B50.9 frozen representation convergence")
    plt.grid(True)
    plt.tight_layout()
    plt.savefig(out / "b50_9_config_convergence.png", dpi=160)
    plt.close()

    plt.figure(figsize=(8, 5))
    plt.plot(thirds_df["third"], thirds_df["observed_mean_percentile"], marker="o")
    plt.axhline(0.5, linestyle="--", linewidth=0.8)
    plt.xticks([1, 2, 3])
    plt.xlabel("source-disjoint corpus contiguous third")
    plt.ylabel("mean physical percentile")
    plt.title("B50.9 thirds robustness")
    plt.grid(True)
    plt.tight_layout()
    plt.savefig(out / "b50_9_thirds_robustness.png", dpi=160)
    plt.close()

    ref_table = pd.DataFrame([
        {"checkpoint": "B50.6", "effect": lineage["b50_6_effect"]},
        {"checkpoint": "B50.7 +75", "effect": lineage["b50_7_effect"]},
        {"checkpoint": "B50.8 mean", "effect": lineage["b50_8_mean_effect"]},
        {"checkpoint": "B50.8 median", "effect": lineage["b50_8_median_effect"]},
        {"checkpoint": "B50.9 independent", "effect": effect},
    ])
    atomic_csv(out / "b50_9_effect_checkpoint_comparison.csv", ref_table)

    plt.figure(figsize=(9, 5))
    xx = np.arange(len(ref_table))
    plt.plot(xx, ref_table["effect"], marker="o")
    plt.axhline(0.0, linestyle="--", linewidth=0.8)
    plt.axhline(THRESHOLDS["primary_effect_max"], linestyle=":", linewidth=0.8)
    plt.xticks(xx, ref_table["checkpoint"], rotation=25, ha="right")
    plt.ylabel("mean physical percentile effect")
    plt.title("B50.9 effect relative to frozen prior checkpoints")
    plt.grid(True)
    plt.tight_layout()
    plt.savefig(out / "b50_9_effect_checkpoint_comparison.png", dpi=160)
    plt.close()

    report = f"""B50.9 — Independent-Corpus Replication
=========================================

Interpretation scope
--------------------
Source-disjoint from B50.6-B50.8: YES
Same representation definition: YES
Frozen training PCA basis: YES
B59/B59.1/B59.2 used: NO
Independent mathematical universe: NO CLAIM

Frozen lineage
--------------
B50.6 verdict                        = {lineage['b50_6_verdict']}
B50.7 verdict                        = {lineage['b50_7_verdict']}
B50.8 verdict                        = {lineage['b50_8_verdict']}
B50.6 effect                         = {lineage['b50_6_effect']}
B50.7 effect                         = {lineage['b50_7_effect']}
B50.8 mean effect                    = {lineage['b50_8_mean_effect']}
frozen input hashes exact            = {frozen_inputs_exact}

Independent corpus
------------------
training operator stack               = {P_train.shape}
independent operator stack            = {P_ext.shape}
prior exposed source segments         = {plan_summary['prior_exposure']['prior_exposed_segment_count']}
independent start segment              = {plan_summary['independent_source']['chosen_start_segment']}
independent end segment                = {plan_summary['independent_source']['chosen_end_segment']}
source disjoint                        = {source_disjoint}
window count                           = {len(P_ext)}
window length / start step             = {plan_summary['training_geometry']['nominal_length']} / {plan_summary['training_geometry']['nominal_step']}
operator dimension exact               = {operator_dim_exact}
frozen PCA parity PASS                 = {pca_parity['pass']}
independent raw-feature parity PASS     = {parity_ok}

Matched-control protocol
------------------------
physical source transitions used       = {len(tis)}
controls per transition                = {args.controls_per_transition}
minimum index separation               = {args.min_index_separation}
matching geometry                      = independent full 4096D operator Euclidean
median |log-distance match error|      = {matching_median}
q90 |log-distance match error|         = {matching_q90}
MATCHING PASS                          = {matching_pass}

Primary independent-corpus replication
--------------------------------------
mean physical percentile               = {primary['observed_mean_percentile']}
median physical percentile             = {primary['observed_median_percentile']}
mean percentile effect vs 0.5          = {primary['observed_mean_effect']}
matched identity p_lower               = {primary['p_lower']}
two-sided p diagnostic                 = {primary['p_two_sided_diagnostic']}
PRIMARY REPLICATION PASS               = {primary_pass}

Frozen representation convergence
---------------------------------
negative-effect config fraction        = {negative_fraction}
CONFIG CONVERGENCE PASS                = {config_pass}

Independent-corpus thirds robustness
------------------------------------
negative thirds                        = {negative_count}/3
nominally replicated thirds            = {nominal_count}/3
THIRDS ROBUSTNESS PASS                 = {thirds_pass}

{thirds_df.to_string(index=False)}

FINAL VERDICT: {verdict}

REASON:
{reason}

Interpretation boundary
-----------------------
This is a source-disjoint data-partition replication relative to every prime
segment exposed to B50.6-B50.8. If the new files were generated by the same
prime-generation pipeline, it is not an independently generated mathematical
universe. No B59/B59.1/B59.2 endpoint is used. No individual-prime prediction,
RH evidence, or theorem claim is made.

Key outputs
-----------
b50_9_prior_exposure_windows.csv
b50_9_independent_source_inventory.csv
b50_9_independent_window_plan.csv
b50_9_plan_summary.json
b50_9_operator_metadata.csv
b50_9_extraction_status.csv
b50_9_extraction_checkpoint.json
b50_9_extraction_manifest.json
b50_9_independent_operator_stack.npz
b50_9_protocol_manifest.json
b50_9_frozen_pca_parity.json
b50_9_independent_raw_feature_parity.csv
b50_9_matching_audit.csv
b50_9_transition_specificity.csv
b50_9_config_specificity.csv
b50_9_primary_null.csv
b50_9_replication_thirds.csv
b50_9_effect_checkpoint_comparison.csv
b50_9_summary.json
b50_9_verdict.txt
b50_9_primary_null.png
b50_9_specificity_by_transition.png
b50_9_config_convergence.png
b50_9_thirds_robustness.png
b50_9_effect_checkpoint_comparison.png
"""
    atomic_text(out / "b50_9_verdict.txt", report)

    print()
    print("=== B50.9 RESULT ===")
    print(f"source disjoint : {source_disjoint}")
    print(f"matching PASS   : {matching_pass}")
    print(f"primary PASS    : {primary_pass}")
    print(f"config PASS     : {config_pass}")
    print(f"thirds PASS     : {thirds_pass}")
    print(f"mean percentile : {primary['observed_mean_percentile']:.6f}")
    print(f"effect vs 0.5   : {effect:.6f}")
    print(f"p_lower         : {primary['p_lower']:.6g}")
    print(f"FINAL VERDICT   : {verdict}")
    print(f"verdict         : {out / 'b50_9_verdict.txt'}")
    return summary


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def parse_args():
    p = argparse.ArgumentParser(description="B50.9 Independent-Corpus Replication")
    p.add_argument("--mode", choices=["plan", "extract", "audit", "all"], default="plan")

    p.add_argument("--b50-7-script", required=True)
    p.add_argument("--state-dataset", required=True)
    p.add_argument("--training-operator-stack", required=True)
    p.add_argument("--b50-script", required=True)
    p.add_argument("--b50-4-script", required=True)
    p.add_argument("--b50-4-protocol", required=True)
    p.add_argument("--b50-4-front-features", required=True)
    p.add_argument("--b50-6-summary", required=True)
    p.add_argument("--b50-7-dir", required=True)
    p.add_argument("--b50-8-dir", required=True)

    p.add_argument(
        "--independent-prime-root",
        default=r"d:\primes_output",
        help=(
            "Directory containing candidate source-disjoint prime segment files. "
            "It may be the same root if the database has been extended with new segment IDs."
        ),
    )
    p.add_argument(
        "--independent-start-segment",
        type=int,
        default=None,
        help=(
            "Engineering override only. Confirmatory default selects the earliest eligible contiguous run. "
            "Supplying this marks the protocol modified."
        ),
    )
    p.add_argument("--target-windows", type=int, default=FROZEN_TARGET_WINDOWS)
    p.add_argument("--output-dir", required=True)

    p.add_argument("--gap-bins", type=int, default=FROZEN_GAP_BINS)
    p.add_argument("--staging-dir", default=None)
    p.add_argument("--reuse-existing", action="store_true")
    p.add_argument("--checkpoint-every", type=int, default=10)

    p.add_argument("--controls-per-transition", type=int, default=FROZEN_CONTROLS)
    p.add_argument("--min-index-separation", type=int, default=FROZEN_MIN_INDEX_SEPARATION)
    p.add_argument("--randomization-replicates", type=int, default=FROZEN_RANDOMIZATION_REPLICATES)
    p.add_argument("--seed", type=int, default=FROZEN_SEED)

    a = p.parse_args()
    if a.target_windows < 6:
        p.error("--target-windows must be >=6")
    if a.gap_bins < 4:
        p.error("--gap-bins must be >=4")
    if a.controls_per_transition < 5:
        p.error("--controls-per-transition must be >=5")
    if a.min_index_separation < 3:
        p.error("--min-index-separation must be >=3")
    if a.randomization_replicates < 999:
        p.error("--randomization-replicates must be >=999")
    if a.checkpoint_every < 1:
        p.error("--checkpoint-every must be >=1")
    return a


def main():
    args = parse_args()
    b507 = import_b507(Path(args.b50_7_script))

    if args.mode == "plan":
        plan_mode(args, b507)
    elif args.mode == "extract":
        extract_mode(args, b507)
    elif args.mode == "audit":
        audit_mode(args, b507)
    elif args.mode == "all":
        plan_mode(args, b507)
        extract_mode(args, b507)
        audit_mode(args, b507)
    else:
        raise ValueError(args.mode)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
